name: 'Tangle'
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.x
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        sudo apt-get update
        sudo apt-get install -y emacs-nox
    - name: Versions
      run: |
        python --version
        emacs --batch -f org-version
        emacs --version
    - name: Clean
      run: |
        rm keyboards/{*,*/*,*/*/*}/keymaps/manna-harbour_miryoku/*
        rm layouts/community/*/manna-harbour_miryoku/*
        rm users/manna-harbour_miryoku/*
        git checkout users/manna-harbour_miryoku/{miryoku,README}.org
        git status -s
    - name: Tangle
      run: |
        emacs --batch -eval '(setq org-confirm-babel-evaluate nil)' -eval "(require 'ob-python)" users/manna-harbour_miryoku/miryoku.org -f org-babel-tangle
    - name: Test
      run: |
        git status -s
        git diff --exit-code
